# Generated by Django 3.0 on 2019-12-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191214_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='poster',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
